version: "3"

services:

  user-db:
    container_name: user-db
    image: mysql
    restart: on-failure
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb

  user_management:
    container_name: user-management
    image: usermanagement:0.0.1-SNAPSHOT.jar
    build: ./UserManagement
    ports:
      - "8083:8083"
    depends_on:
      - user-db
    environment:
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.datasource.url=jdbc:mysql://user-db:3306/userdb?autoreconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update