version: "3"

services:

  order-db:
    container_name: order-db
    image: mysql
    restart: on-failure
    ports:
      - "3302:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderdb

  order_management:
    container_name: order-management
    image: ordermanagement:0.0.1-SNAPSHOT.jar
    build: ./OrderManagement
    ports:
      - "8082:8082"
    depends_on:
      - order-db
    environment:
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.datasource.url=jdbc:mysql://order-db:3306/orderdb?autoreconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update