version: "3"

services:

  promotion-db:
    container_name: promotion-db
    image: mysql
    restart: on-failure
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: promotiondb

  promotion_management:
    container_name: promotion-management
    image: promotionmanagement:0.0.1-SNAPSHOT.jar
    build: ./PromotionManagement
    ports:
      - "8085:8085"
    depends_on:
      - promotion-db
    environment:
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.datasource.url=jdbc:mysql://promotion-db:3306/promotiondb?autoreconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update